esphome:
    name: rotex
    friendly_name: Rotex
    platformio_options:
        build_unflags:
            - "-std=gnu++11"
            - "-fno-exceptions"
        build_flags:
            - "-std=gnu++17"
            - "-fexceptions"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source: github://wrfz/esphome-daikin-rotex-can

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "DaikinRotex Fallback Hotspot"
    password: !secret fallback_hotspot_password

canbus:
  - platform: esp32_can
    id: can_bus
    can_id: 0x680
    rx_pin: GPIO2
    tx_pin: GPIO3
    bit_rate: 20kbps

daikin_rotex_can:
  id: rotext_hpsu_compact_508
  canbus_id: can_bus
  log_filter:
    name: "Log Filter"
  entities:
    bypass_valve:
      name: "BPV"
    circulation_pump:
      name: "Umwaelzpumpe"
    dhw_mixer_position:
      name: "DHW Mischer Position"
    ehs_for_ch:
      name: "EHS fuer CH"
    error_code:
      name: "Fehlercode"
    flow_temperature_day:
      name: "T Vorlauf Tag"
    flow_temperature_day_set:
      name: "T Vorlauf Tag Einstellen"
    heating_curve:
      name: "Heizkurve"
    heating_curve_set:
      name: "Heizkurve Einstellen"
    hk_function:
      name: "HK-Funktion"
    hk_function_select:
      name: "HK Funktion"
    max_target_supply_temperature:
      name: "Max VL Soll"
    min_target_supply_temperature:
      name: "Min VL Soll"
    mode_of_operation:
      name: "Betriebsart"
    operating_mode:
      name: "Betriebsmodus"
    operating_mode_select:
      name: "Betriebsmodus setzen"
    runtime_compressor:
      name: "Laufzeit Compressor"
    runtime_pump:
      name: "Laufzeit Pump"
    sg_mode:
      name: "SG Modus"
    smart_grid:
      name: "Smart Grid"
    spreizung_mod_hz:
      name: "Spreizung MOD HZ"
    spreizung_mod_ww:
      name: "Spreizung MOD WW"
    status_kesselpumpe:
      name: "Status Kesselpumpe"
    status_kompressor:
      name: "Status Kompressor"
    tdhw1:
      name: "Warmwassertemperatur"
    temperature_outside:
      name: "Aussentemperatur"
    tr:
      name: "Ruecklauftemperatur Heizung"
    tv:
      name: "Heizkreis Vorlauf (TV)"
    tvbh:
      name: "Vorlauftemperatur Heizung (TVBH)"
    water_flow:
      name: "Durchfluss"
    water_pressure:
      name: "Wasserdruck"
    target_hot_water_temperature:
      name: "T-WW-Soll1"
    target_supply_temperature:
      name: "Vorlauf Soll"
    thermal_power:
      name: "Thermische Leistung"
    total_energy_produced:
      name: "Erzeugte Energie Gesamt"
