name: Compile ESPHome Binary

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'examples/full.yaml'
      - 'components/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check for required secrets
        run: |
          if [ -z "${{ secrets.API_ENCRYPTION_KEY }}" ]; then
            echo "Error: API_ENCRYPTION_KEY secret is not set" >&2
            exit 1
          fi
          if [ -z "${{ secrets.OTA_PASSWORD }}" ]; then
            echo "Error: OTA_PASSWORD secret is not set" >&2
            exit 1
          fi
          if [ -z "${{ secrets.WIFI_SSID }}" ]; then
            echo "Error: WIFI_SSID secret is not set" >&2
            exit 1
          fi
          if [ -z "${{ secrets.WIFI_PASSWORD }}" ]; then
            echo "Error: WIFI_PASSWORD secret is not set" >&2
            exit 1
          fi
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set environment variables 
        run: | 
          echo "API_ENCRYPTION_KEY=${{ secrets.API_ENCRYPTION_KEY }}" >> $GITHUB_ENV
          echo "OTA_PASSWORD=${{ secrets.OTA_PASSWORD }}" >> $GITHUB_ENV
          echo "WIFI_SSID=${{ secrets.WIFI_SSID }}" >> $GITHUB_ENV
          echo "WIFI_PASSWORD=${{ secrets.WIFI_PASSWORD }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "DATE=$(date +%Y%m%d_%H%M)" >> $GITHUB_ENV
          
      - name: Install ESPHome
        run: |
          python -m pip install esphome

      - name: Compile ESPHome binary
        run: |
          cp .github/workflows/resources/secrets.yaml .
          esphome compile examples/full.yaml
          mv examples/.esphome/build/rotex/.pioenvs/rotex/firmware.factory.bin examples/.esphome/build/rotex/.pioenvs/rotex/rotex.factory-gpios-tx05-rx06_${BRANCH_NAME}_${DATE}.bin  

      - name: Archive compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: examples/.esphome/build/rotex/.pioenvs/rotex/rotex.factory-gpios-tx05-rx06_*.bin
