name: Manually Triggered Workflow with Checkboxes

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
        default: 'default_value'
      param2:
        description: 'Parameter 2'
        required: false
        default: 'optional_value'
      checkbox1:
        description: 'Checkbox 1'
        required: true
        type: boolean
        default: false
      checkbox2:
        description: 'Checkbox 2'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install cells
      run: |      
        wget https://files.pythonhosted.org/packages/18/82/14819c1cc67c67e909abdbd9824eb756adccd47a1dee1c846f7300716646/cels-0.3.1.tar.gz
        python3 -m pip install cels-0.3.1.tar.gz


    - name: Run a script
      run: |
        echo "Running a script with param1=${{ github.event.inputs.param1 }} and param2=${{ github.event.inputs.param2 }}"
        if ${{ github.event.inputs.checkbox1 }}; then
          echo "Checkbox 1 is checked"
        else
          echo "Checkbox 1 is not checked"
        fi
        if ${{ github.event.inputs.checkbox2 }}; then
          echo "Checkbox 2 is checked"
        else
          echo "Checkbox 2 is not checked"
        fi
        cp .github/workflows/src/extract_external_components_block.py .
        cp examples/full.yaml .
        cp .github/workflows/src/patch_full_yaml.sh .
        echo "path of build script: `pwd`"
        # patch full.yaml to load external components from dev
        if [ "${{ github.ref }}" == "refs/heads/dev" ]; then 
          echo "This step runs only on the dev branch"            
          source patch_full_yaml.sh
        else 
          echo "This step does not run on the dev branch" 
        fi

        # print path used for external components
        echo "The following external components will be used for compilation: "
        python extract_external_components_block.py
